In [1]:
import polars as pl

In [2]:
df_GDSC1 = pl.DataFrame(pl.read_excel("data/GDSC1.xlsx"))
df_GDSC1

shape: (333_161, 16)
┌─────────┬─────────────┬────────────┬────────────┬───┬──────────┬──────────┬──────────┬───────────┐
│ DATASET ┆ NLME_RESULT ┆ NLME_CURVE ┆ CELL_LINE_ ┆ … ┆ LN_IC50  ┆ AUC      ┆ RMSE     ┆ Z_SCORE   │
│ ---     ┆ _ID         ┆ _ID        ┆ NAME       ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---       │
│ str     ┆ ---         ┆ ---        ┆ ---        ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64       │
│         ┆ i64         ┆ i64        ┆ str        ┆   ┆          ┆          ┆          ┆           │
╞═════════╪═════════════╪════════════╪════════════╪═══╪══════════╪══════════╪══════════╪═══════════╡
│ GDSC1   ┆ 342         ┆ 15580432   ┆ ES5        ┆ … ┆ 3.966813 ┆ 0.985678 ┆ 0.026081 ┆ 1.299144  │
│ GDSC1   ┆ 342         ┆ 15580806   ┆ ES7        ┆ … ┆ 2.69209  ┆ 0.97269  ┆ 0.110059 ┆ 0.156076  │
│ GDSC1   ┆ 342         ┆ 15581198   ┆ EW-11      ┆ … ┆ 2.47799  ┆ 0.944459 ┆ 0.087019 ┆ -0.035912 │
│ GDSC1   ┆ 342         ┆ 15581542   ┆ SK-ES-1    ┆ … ┆ 2.033564 ┆ 0.950758 ┆ 0.01629  ┆ -0.434437 │
│ GDSC1   ┆ 342         ┆ 15581930   ┆ COLO-829   ┆ … ┆ 2.966007 ┆ 0.954778 ┆ 0.180255 ┆ 0.401702  │
│ …       ┆ …           ┆ …          ┆ …          ┆ … ┆ …        ┆ …        ┆ …        ┆ …         │
│ GDSC1   ┆ 342         ┆ 15911377   ┆ SNU-1040   ┆ … ┆ 5.085294 ┆ 0.972251 ┆ 0.040661 ┆ 0.860626  │
│ GDSC1   ┆ 342         ┆ 15912122   ┆ SNU-61     ┆ … ┆ 5.725399 ┆ 0.976109 ┆ 0.045453 ┆ 1.785602  │
│ GDSC1   ┆ 342         ┆ 15912431   ┆ SNU-81     ┆ … ┆ 4.930753 ┆ 0.970851 ┆ 0.038612 ┆ 0.637308  │
│ GDSC1   ┆ 342         ┆ 15912739   ┆ SNU-C5     ┆ … ┆ 4.551784 ┆ 0.97233  ┆ 0.042649 ┆ 0.089683  │
│ GDSC1   ┆ 342         ┆ 15913046   ┆ DiFi       ┆ … ┆ 4.681069 ┆ 0.980906 ┆ 0.015312 ┆ 0.276505  │
└─────────┴─────────────┴────────────┴────────────┴───┴──────────┴──────────┴──────────┴───────────┘

In [3]:
df_GDSC2 = pl.DataFrame(pl.read_excel("data/GDSC2.xlsx"))
df_GDSC2

shape: (242_036, 16)
┌─────────┬────────────┬────────────┬────────────┬───┬───────────┬──────────┬──────────┬───────────┐
│ DATASET ┆ NLME_RESUL ┆ NLME_CURVE ┆ CELL_LINE_ ┆ … ┆ LN_IC50   ┆ AUC      ┆ RMSE     ┆ Z_SCORE   │
│ ---     ┆ T_ID       ┆ _ID        ┆ NAME       ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---       │
│ str     ┆ ---        ┆ ---        ┆ ---        ┆   ┆ f64       ┆ f64      ┆ f64      ┆ f64       │
│         ┆ i64        ┆ i64        ┆ str        ┆   ┆           ┆          ┆          ┆           │
╞═════════╪════════════╪════════════╪════════════╪═══╪═══════════╪══════════╪══════════╪═══════════╡
│ GDSC2   ┆ 343        ┆ 15946310   ┆ PFSK-1     ┆ … ┆ -1.463887 ┆ 0.93022  ┆ 0.089052 ┆ 0.433123  │
│ GDSC2   ┆ 343        ┆ 15946548   ┆ A673       ┆ … ┆ -4.869455 ┆ 0.61497  ┆ 0.111351 ┆ -1.4211   │
│ GDSC2   ┆ 343        ┆ 15946830   ┆ ES5        ┆ … ┆ -3.360586 ┆ 0.791072 ┆ 0.142855 ┆ -0.599569 │
│ GDSC2   ┆ 343        ┆ 15947087   ┆ ES7        ┆ … ┆ -5.04494  ┆ 0.59266  ┆ 0.135539 ┆ -1.516647 │
│ GDSC2   ┆ 343        ┆ 15947369   ┆ EW-11      ┆ … ┆ -3.741991 ┆ 0.734047 ┆ 0.128059 ┆ -0.807232 │
│ …       ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …        ┆ …        ┆ …         │
│ GDSC2   ┆ 343        ┆ 16188242   ┆ SNU-175    ┆ … ┆ 10.127082 ┆ 0.976746 ┆ 0.074498 ┆ 0.156872  │
│ GDSC2   ┆ 343        ┆ 16188695   ┆ SNU-407    ┆ … ┆ 8.576377  ┆ 0.913378 ┆ 0.057821 ┆ -1.626959 │
│ GDSC2   ┆ 343        ┆ 16188953   ┆ SNU-61     ┆ … ┆ 10.519636 ┆ 0.975001 ┆ 0.05809  ┆ 0.608442  │
│ GDSC2   ┆ 343        ┆ 16189493   ┆ SNU-C5     ┆ … ┆ 10.694579 ┆ 0.969969 ┆ 0.101013 ┆ 0.809684  │
│ GDSC2   ┆ 343        ┆ 16189775   ┆ DiFi       ┆ … ┆ 10.034825 ┆ 0.966988 ┆ 0.089057 ┆ 0.050746  │
└─────────┴────────────┴────────────┴────────────┴───┴───────────┴──────────┴──────────┴───────────┘

In [4]:
# 2. Fusion et suppression des doublons en utilisant la colonne "DATASET"
df_GDSC = (
    pl.concat([df_GDSC1, df_GDSC2], how="diagonal")
    .sort("DATASET", descending=True) # "GDSC2" passera toujours au-dessus de "GDSC1"
    .unique(subset=["CELL_LINE_NAME", "DRUG_NAME"], keep="first")
)

# 3. Affichage
print(f"Lignes GDSC1 : {df_GDSC1.height}")
print(f"Lignes GDSC2 : {df_GDSC2.height}")
print(f"Lignes du Master Dataset fusionné et nettoyé : {df_GDSC.height}")

Lignes GDSC1 : 333161
Lignes GDSC2 : 242036
Lignes du Master Dataset fusionné et nettoyé : 461365

In [12]:
df_GDSC

shape: (461_365, 16)
┌─────────┬────────────┬────────────┬────────────┬───┬───────────┬──────────┬──────────┬───────────┐
│ DATASET ┆ NLME_RESUL ┆ NLME_CURVE ┆ CELL_LINE_ ┆ … ┆ LN_IC50   ┆ AUC      ┆ RMSE     ┆ Z_SCORE   │
│ ---     ┆ T_ID       ┆ _ID        ┆ NAME       ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---       │
│ str     ┆ ---        ┆ ---        ┆ ---        ┆   ┆ f64       ┆ f64      ┆ f64      ┆ f64       │
│         ┆ i64        ┆ i64        ┆ str        ┆   ┆           ┆          ┆          ┆           │
╞═════════╪════════════╪════════════╪════════════╪═══╪═══════════╪══════════╪══════════╪═══════════╡
│ GDSC1   ┆ 342        ┆ 15600538   ┆ NCI-H82    ┆ … ┆ -0.140674 ┆ 0.820852 ┆ 0.147322 ┆ -0.210958 │
│ GDSC2   ┆ 343        ┆ 15951226   ┆ GB-1       ┆ … ┆ 3.232005  ┆ 0.963956 ┆ 0.075839 ┆ 0.657996  │
│ GDSC2   ┆ 343        ┆ 15991332   ┆ MCF7       ┆ … ┆ 6.875959  ┆ 0.9743   ┆ 0.072238 ┆ 1.367293  │
│ GDSC1   ┆ 342        ┆ 15582306   ┆ COLO-829   ┆ … ┆ 4.714267  ┆ 0.97391  ┆ 0.058732 ┆ 1.383729  │
│ GDSC1   ┆ 342        ┆ 15610477   ┆ SHP-77     ┆ … ┆ -2.229306 ┆ 0.587243 ┆ 0.062027 ┆ 0.590662  │
│ …       ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …        ┆ …        ┆ …         │
│ GDSC2   ┆ 343        ┆ 16047396   ┆ ML-2       ┆ … ┆ -3.245473 ┆ 0.222401 ┆ 0.097853 ┆ -2.499111 │
│ GDSC2   ┆ 343        ┆ 16166867   ┆ HCC-33     ┆ … ┆ 3.18403   ┆ 0.938204 ┆ 0.136701 ┆ -1.557273 │
│ GDSC2   ┆ 343        ┆ 15971456   ┆ HCC2157    ┆ … ┆ 4.894122  ┆ 0.989773 ┆ 0.139894 ┆ -0.28403  │
│ GDSC1   ┆ 342        ┆ 15825223   ┆ BICR22     ┆ … ┆ 5.708223  ┆ 0.982658 ┆ 0.054317 ┆ 0.493314  │
│ GDSC1   ┆ 342        ┆ 15902271   ┆ JHOS-2     ┆ … ┆ 0.546158  ┆ 0.547493 ┆ 0.113338 ┆ 0.168934  │
└─────────┴────────────┴────────────┴────────────┴───┴───────────┴──────────┴──────────┴───────────┘

In [14]:
df_GDSC.write_csv("data/Dataset_GDSC.csv")